#!/bin/sh
# Copyright (C) 2013 Tulio Magno Quites Machado Filho <tuliom@quites.com.br>

bin="/etc/init.d/aiccu"
log="logger -t hotplug -p"

if [ "$INTERFACE" != "wan" ]; then
	exit 0
fi

case $ACTION in
	"ifup")
		sleep 5
		$log 6 "Restarting aiccu..."
		$bin restart
		;;
	"ifdown")
		$log 6 "Stopping aiccu..."
		$bin stop
		;;
esac
